server:
  port: 8080

spring:
  application:
    name: rent_read
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/crio-rent_read
    username: root
    password: root@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  output:
    ansi:
      enabled: always